--  Configuration for npu_layer_worst_case_timings generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Npu_Layer_Worst_Case_Timings_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0-dev";
   Crate_Name : constant String := "npu_layer_worst_case_timings";

   Alire_Host_OS : constant String := "windows";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "msys2";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Npu_Layer_Worst_Case_Timings_Config;
