/* Configuration for npu_layer_worst_case_timings generated by Alire */
#ifndef NPU_LAYER_WORST_CASE_TIMINGS_CONFIG_H
#define NPU_LAYER_WORST_CASE_TIMINGS_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "npu_layer_worst_case_timings"

#define ALIRE_HOST_OS "windows"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "msys2"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
