# =====================================================================
# Create a Lattice Diamond project for NEORV32 on ECP5-EVN
#
# Usage example (batch):
#   /path/to/diamond.sh -t create_neorv32_diamond.tcl
#
# Then open the generated .ldf in the GUI, or extend this script with
# synthesis/PAR run commands as needed.
# =====================================================================

# ---------------- User configuration ---------------------------------

# Directory of this script (so relative paths are well-defined)
set script_dir [file normalize [file dirname [info script]]]
cd $script_dir

# NEORV32 repo root (relative to this script)
# Adjust if your tree is laid out differently.
set neorv32_home [file normalize "../../neorv32"]

# Project/implementation names
set board_name "ECP5EVN"
set proj_name  "${board_name}_NEORV32_MinimalBoot"
set impl_name  "impl1"

# Exact ECP5 device (adjust if Diamond uses a slightly different string)
set device "LFE5U5MG-85F-8BG381I"

# Work directory where the Diamond project (.ldf, etc.) will live
set work_dir "work"

# Constraint file (LPF) – adjust path/name as needed
# Here we assume the LPF is next to this script.
set lpf_file [file normalize "$script_dir/ECP5EVN_NEORV32_MinimalBoot.lpf"]

# Board top-level file (place this VHDL next to this script)
set board_top_src [file normalize "$script_dir/neorv32_ECP5EVN_BoardTop_MinimalBoot.vhd"]

# Processor template inside NEORV32 repo
# If you want to use a local modified copy instead, point this to that path.
set proc_template [file normalize "$neorv32_home/rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd"]

# NEORV32 file list (SoC setup) generated by rtl/generate_file_lists.sh
set file_list_path [file normalize "$neorv32_home/rtl/file_list_soc.f"]

# ---------------- Prepare work directory ------------------------------

if {![file exists $work_dir]} {
  file mkdir $work_dir
  puts "Created directory $work_dir"
} else {
  set files [glob -nocomplain "$work_dir/*"]
  if {[llength $files] != 0} {
    puts "Cleaning directory $work_dir"
    file delete -force {*}$files
  } else {
    puts "$work_dir is already empty"
  }
}

# Change into work dir so project files end up here
cd $work_dir

# ---------------- Create Diamond project ------------------------------

# Create a new project with the given device and implementation.
# If your Diamond version uses different flags, check 'help prj_project'
# in the Diamond Tcl console and adjust this line accordingly.
prj_project new -name $proj_name -impl $impl_name -dev $device

# ---------------- Add NEORV32 core + SoC sources ----------------------

if {![file exists $file_list_path]} {
  puts "ERROR: Cannot find NEORV32 file list: $file_list_path"
  return
}

# Read file_list_soc.f produced by generate_file_lists.sh
set fl_fd [open $file_list_path r]
set fl_data [read $fl_fd]
close $fl_fd

# Replace placeholder path with actual rtl directory as described in the docs
#set fl_data [string map {"NEORV32_RTL_PATH_PLACEHOLDER" "$neorv32_home/rtl"} $fl_data]

# NEW (correct: build the map with variable expansion)
set fl_data [string map [list "NEORV32_RTL_PATH_PLACEHOLDER" "$neorv32_home/rtl"] $fl_data]

# Collect file paths, ignoring empty lines and comments
set neorv32_files {}
foreach line [split $fl_data "\n"] {
  set trimmed [string trim $line]
  if {$trimmed eq ""} {
    continue
  }
  if {[string match "#*" $trimmed]} {
    continue
  }
  lappend neorv32_files $trimmed
}

puts "Adding NEORV32 RTL files to library 'neorv32'..."
foreach f $neorv32_files {
  if {![file exists $f]} {
    puts "WARNING: NEORV32 file not found: $f"
    continue
  }
  # Add each NEORV32 file into VHDL library 'neorv32' in GHDL's elab order
  prj_src add -work neorv32 $f
}

# Ensure the processor template is present (in case it's not in file_list_soc.f)
if {[file exists $proc_template]} {
  puts "Adding processor template: $proc_template"
  prj_src add -work neorv32 $proc_template
} else {
  puts "WARNING: Processor template not found: $proc_template"
}

# ---------------- Add board-level top entity --------------------------

if {![file exists $board_top_src]} {
  puts "ERROR: Board top-level file not found: $board_top_src"
  return
}

puts "Adding board top-level: $board_top_src"

# Board-level top can be in 'work' (it instantiates the NEORV32 template)
prj_src add -work work $board_top_src
prj_src top $board_top_src

# ---------------- Add constraints (LPF) -------------------------------

if {[file exists $lpf_file]} {
  puts "Adding constraints file: $lpf_file"
  prj_src add $lpf_file
} else {
  puts "WARNING: Constraint file not found: $lpf_file"
}

# ---------------- Save project ----------------------------------------

prj_project save

puts "==================================================================="
puts "NEORV32 Diamond project created:"
puts "  Project:        $proj_name"
puts "  Implementation: $impl_name"
puts "  Device:         $device"
puts "  Location:       [pwd]"
puts "Now open the .ldf in Diamond and run Synthesis / Map / PAR / Bitgen."
puts "==================================================================="

